genetic_algorithm:
  elite_size: 16
  batch_size: 16
  ga_epochs: 5
  adaptive: true
  train_epochs_per_ga: 2
  use_harmonic_mean: true
  checkpoint_freq: -1
  num_scale_factor: 1.2  # Generate 1x the elite population size for better diversity
  
  # Blend mode configuration (optional - enables hybrid fixed/adaptive strategy)
  # Uncomment the line below to enable blend mode:
  # blend_pattern: "f2-a2"  # Pattern: 2 epochs fixed, 2 epochs adaptive, repeat
  
  # Other blend pattern examples:
  # blend_pattern: "f1-a1"  # Alternating: Fixed, Adaptive, Fixed, Adaptive...
  # blend_pattern: "f3-a1"  # 3 Fixed epochs, then 1 Adaptive, repeat
  # blend_pattern: "f1-a3"  # 1 Fixed epoch, then 3 Adaptive, repeat

scaffold:
  fine_tune_epochs: 20  # Number of epochs for scaffold fine-tuning
  scale_factor: 2  # Generate 2x the elite population size for scaffold-based molecule generation
  positioning_strategy: plane_through_origin  # Scaffold positioning strategy: plane_through_origin, free_position, sphere_constraint, center_only

sampling_parameters:
  n_steps: 1000  # Number of diffusion timesteps - should match model config
  step_lr: 1.0e-6
  w_global_pos: 1.0
  w_global_node: 4.0
  w_local_pos: 1.0
  w_local_node: 5.0
  global_start_sigma: !!float 'inf'
  clip: 1000.0
  clip_local: null
  sampling_type: "generalized"
  eta: 1.0

scoring_operator:
  scoring_names:
    - logp
    - qed
    - sa
    - tpsa
  
  selection_names:
    - logp
    - qed
    - sa
    - tpsa
  
  property_config:
    logp:
      range: [-4, 7]
      preferred_value: 2
    qed:
      range: [0, 1]
      higher_is_better: true
    sa:
      range: [1, 10]
      higher_is_better: false
    tpsa:
      range: [0, 188]
      preferred_value: 90  # 25th-75th percentile from MOSES test set

  scoring_parameters:
    sa_model: SA_data/SA_score.pkl.gz

output_config:
  output_dir: ./ga_output/qm40_logp_qed_sa 